BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "ZooAnimal" (
	"Id"	INTEGER NOT NULL,
	"ZooId"	INTEGER NOT NULL,
	"AnimalId"	INTEGER NOT NULL,
	CONSTRAINT "ZooFK" FOREIGN KEY("ZooId") REFERENCES "Zoo"("Id"),
	CONSTRAINT "AnimalFK" FOREIGN KEY("AnimalId") REFERENCES "Animal"("Id"),
	PRIMARY KEY("Id" AUTOINCREMENT)
);
INSERT INTO "ZooAnimal" VALUES (3,1,1);
INSERT INTO "ZooAnimal" VALUES (4,1,2);
INSERT INTO "ZooAnimal" VALUES (5,2,3);
INSERT INTO "ZooAnimal" VALUES (6,2,4);
INSERT INTO "ZooAnimal" VALUES (7,3,5);
INSERT INTO "ZooAnimal" VALUES (8,3,6);
INSERT INTO "ZooAnimal" VALUES (9,4,7);
INSERT INTO "ZooAnimal" VALUES (10,4,8);
INSERT INTO "ZooAnimal" VALUES (11,5,1);
INSERT INTO "ZooAnimal" VALUES (12,5,2);
INSERT INTO "ZooAnimal" VALUES (13,5,3);
INSERT INTO "ZooAnimal" VALUES (14,5,4);
INSERT INTO "ZooAnimal" VALUES (15,5,5);
INSERT INTO "ZooAnimal" VALUES (16,5,6);
INSERT INTO "ZooAnimal" VALUES (17,5,7);
INSERT INTO "ZooAnimal" VALUES (18,5,8);
COMMIT;
